name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start Build"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            print("Directory contents:")
            regex_list={
                "SSN":re.compile("\d{3}-?\d{2}-?\d{4}")
            }
            for f in os.listdir():
                print(f)
                for i in regex_list:
                    for j, line in enumerate(open(f)):
                        for match in re.finditer(regex_list[i], line):
                            print("Found  " + i + " in " + fileIn + " on line: " + str(j+1) + " " + match.group() ) #regex_list[i])
                            return -1
